### ISSUE TITLE
Cannot set Enami data to HTML DOM Elements using JavaScript

### ISSUE THREAD

**Issue by JarisGV** [EnzoEmb/enami#10]
Hello, @EnzoEmb. How's it going?

In order to keep DOM Elements clean I use to append animation classes and datasets via javascript.
I'm testing Enami to animate some HTML elements but I found the following error:
The elements only get animated if I declare `data-enami-children=""` inline. If I remove it, the animation won't start. Curiously, the attribute doesn't need to have the same value from javascript code. 

HTML Code:
`
< div id="demo" class="demo" data-enami-children="anything-here">
`
Javascript Code:

`
att('.staggering > #demo', {'class':'demo','data-enami-animation':'fade-up','data-enami-children':'.demo-dot','data-enami-stagger':'.2s'});
`

You can check this out in action in this Pen:
https://codepen.io/byJaris/pen/bGOpEZZ

Is there a way to resolve this?

Thanks in advance and congrats for Enami.js

**Comment by EnzoEmb** [comment]
Hi @jarisgv,

It seems that moving the initialization of enami after adding the attributes solves the issue:
https://codepen.io/enzoemb/pen/gOZrrRy

Also, i will be checking whats going on with the `data-enami-children` issue later 🤔 🤔

Thanks for your comments! 😊

**Comment by JarisGV** [comment]
Thanks a lot !!!
⭐⭐⭐⭐⭐
